# Generated by Django 4.1.7 on 2023-03-28 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_postform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postform',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
