# Generated by Django 4.1.7 on 2023-03-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_create_at_postform_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='upForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='')),
                ('body', models.TextField()),
            ],
        ),
    ]
